s3 {
  lake-path = "s3a://smart-water-readings/lake/"
  access-key = "S3_ACCESS_KEY"
  secret-key = "S3_SECRET_KEY"
  reports-path   = "s3a://smart-water-readings/reports"
}

mysql {
  url = "jdbc:mysql://DB_URL:3306/DB_NAME"
  username = "DB_USERNAME"
  password = "DB_PASSWORD"
}
