s3 {
    bucket = "s3-bucket-name"
    accessKey = "XXXXXXXXXXXCDY7ZPFG"
    secretKey = "CXE9Go2wZZ8KO5Oc3f1FWTTyqXXXXXXXXXXXXXXX"
}

kafka {
  bootstrapServer = "localhost:9092"
  topic = "orders_avro_topic"
}

mysql {
  url = "jdbc:mysql://rds.amazonaws.com:3306/db_name"
  username = "admin"
  password = "password"
}

cassandra {
  username = "cassandra-username"
  password = "tTUhRxiJfPThWXCd4JD0f7IM3oOTtowXXXXXXXXXXXXXXXXXXXXXXXXX="
}

truststore {
    password = "changeit"
}