streaming {
  kafka-bootstrap = "localhost:9092"
  topic = "smart_water_readings"

  # local path
  lake-path = "lake"
  recent-json-path = "recent_readings"

  checkpoint = "chk/streaming"
}
s3 {
    accessKey = "S3_ACCESS_KEY"
    secretKey = "S3_SECRET_KEY"

    checkpoint = "s3a://smart-water-readings/checkpoint/streaming"
    lake-path = "s3a://smart-water-readings/lake"
    recent-json-path = "s3a://smart-water-readings/recent_readings"
}