play.filters.enabled += "play.filters.cors.CORSFilter"

play.filters.cors {
  pathPrefixes = ["/"]
  allowedOrigins = ["*"]
  allowedHttpMethods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
  allowedHttpHeaders = ["Accept", "Origin", "Content-Type", "X-Auth-Token", "Authorization"]
}

db.default.driver = com.mysql.cj.jdbc.Driver
db.default.url = "jdbc:mysql://DB_URL:3306/DB_NAME"
db.default.username = "DB_USERNAME"
db.default.password = "DB_PASSWORD"

slick.dbs.default.profile = "slick.jdbc.MySQLProfile$"
slick.dbs.default.db.driver = ${db.default.driver}
slick.dbs.default.db.url = ${db.default.url}
slick.dbs.default.db.user = ${db.default.username}
slick.dbs.default.db.password = ${db.default.password}

# s3 paths (use s3a:// format)
s3.recentReadingsPath = "s3a://smart-water-readings/recent_readings"
s3.reportsBasePath    = "s3a://smart-water-readings/reports"

play.http.parser.maxMemoryBuffer=20MB

aws.accessKey = "S3_ACCESS_KEY"
aws.secretKey = "S3_SECRET_KEY"
aws.region    = "S3_REGION"


play.http.filters = "filters.Filters"